services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  wordpress:
    image: wordpress:6.5-php8.2
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      # Плагин (разрабатываем локально)
      - ./src/company-contact-form:/var/www/html/wp-content/plugins/company-contact-form
      
      # Конфиги (явно монтируем нужные файлы)
      - ./docker-configs/wp-config.php:/var/www/html/wp-config.php
      - ./docker-configs/wp-cli.yml:/var/www/html/wp-cli.yml
      
      # Загрузки, апдейты, кеш (то, что реально нужно сохранять)
      - wp_data:/var/www/html/wp-content/uploads
      - wp_data:/var/www/html/wp-content/upgrade
      - wp_data:/var/www/html/wp-content/cache
    ports:
      - "8888:80"
    entrypoint: ["/bin/sh", "-c", "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && docker-entrypoint.sh apache2-foreground"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
  wp_data:
